### ISSUE TITLE
Incompatibility with Pehkui

### ISSUE THREAD

**Issue by BellaRosaGonzalez** [Wilyicaro/Factocrafty#1]
Game Crashes when both are loaded

**Comment by Wilyicaro** [comment]
In my tests, the Pehkui mod has no loading problems with Factocrafty in Fabric and Forge, if you present the crash report it might be more useful

**Comment by Wilyicaro** [comment]
Sorry for the delay in responding. This incompatibility is not with Pehkui but with Bewitchment, anyway it will be fixed in the next update
