### ISSUE TITLE
recipes not showing in REI or JEI[Bug/Glitch]

### ISSUE THREAD

**Issue by MasonWilly** [Wilyicaro/Factocrafty#2]
*Italic* = Optional

**Mod Version-Minecraft Version**

Mod Loader Version

**Bug/Glitch Occurrence Context**

*Crash Report

**What happened wrong**

**Comment by Wilyicaro** [comment]
Factocrafty recipes do show in JEI, both machine recipe categories and available item recipes, however currently there is no full REI support, you may have seen items that still do not have recipes, although functional, as they have no use in this state of development, such as more advanced versions of liquid tanks and energy storages
