### ISSUE TITLE
how do i get sticky resin?

### ISSUE THREAD

**Issue by MasonWilly** [Wilyicaro/Factocrafty#3]
*Italic* = Optional

**Mod Version-Minecraft Version**

Mod Loader Version

**Bug/Glitch Occurrence Context**

*Crash Report

**What happened wrong**

**Comment by Wilyicaro** [comment]
Sorry for the lack of a Wiki, I'm working on creating one. 
To get sticky resin initially, it is necessary to strip a rubber log (possible to find in swamps, dark oak forests and taigas) and then with the axe use the right button again to cut it and have a chance of ~35% to drop sticky resin. 
It is also possible with the use of the extractor and rubber logs, or with the latex extracted with the treetap towards a cut stripped rubber log.
