### ISSUE TITLE
My server crashes when i refine graphite ingots[Bug/Glitch]

### ISSUE THREAD

**Issue by MasonWilly** [Wilyicaro/Factocrafty#5]
*Italic* = Optional

**Mod Version-Minecraft Version**

Mod Loader Version

**Bug/Glitch Occurrence Context**

*Crash Report

**What happened wrong**

**Comment by Wilyicaro** [comment]
If possible, send the crash report of the server, it'll be helpful

**Comment by MasonWilly** [comment]
it happens when i extract rubber logs to resin too.

**Comment by MasonWilly** [comment]
![image](https://github.com/Wilyicaro/Factocrafty/assets/140833403/c642d869-73f4-4aae-ac24-28c7aa98280e)

1.20.1 - I have applied energistics 2

**Comment by Wilyicaro** [comment]
Sorry but I'm not seeing any crash in this image

**Comment by MasonWilly** [comment]
[crash-2023-07-29_21.23.28-server.txt](https://github.com/Wilyicaro/Factocrafty/files/12208055/crash-2023-07-29_21.23.28-server.txt)
sorry for taking so long but i really enjoy this mod and i would hate to have to take it off my server. is there any way this could be fixed?

**Comment by Wilyicaro** [comment]
Thank you very much for making the crash report available, it will be fixed in the next version, it is a Fabric exclusive bug.
