### ISSUE TITLE
[Bug/Glitch]

### ISSUE THREAD

**Issue by happyburger23** [Wilyicaro/Factocrafty#6]
*Italic* = Optional

**Factocrafty-1.20.1-0.0.0.3-fabric and FactoryAPI-1.20.1-0.1.9.1-fabric**

*Mod Loader:* fabric-loader 0.14.21-1.20.1

**Bug/Glitch Occurrence Context**

[crash-2023-07-29_21.48.27-client.txt](https://github.com/Wilyicaro/Factocrafty/files/12208358/crash-2023-07-29_21.48.27-client.txt)

**What happened wrong**
Opened creative inventory. Happens every time.

**Comment by Wilyicaro** [comment]
Sorry for the inconvenience, this version was not meant to be publicly available, I had archived it, but CurseForge posted it anyway. If you go back to 1.20.1-0.1.9 it will work normally
