### ISSUE TITLE
[General Question] Is there a social place for this mod?

### ISSUE THREAD

**Issue by KirboSoftware** [Wilyicaro/Factocrafty#7]
Hey, I wondered if there was a discord server or something related to get updates through that as I'm following this mod for a while and would like to follow it more!

Lots of love ❤️ and keep on developing!

**Comment by Wilyicaro** [comment]
There is still no discord for Factocrafty, but that's the plan, even to help in the creative process with suggestions, ideas, etc.  
Thanks for following the project :)

**Comment by KirboSoftware** [comment]
I will look forward to the development of the mod as I'm currently creating a modpack and wanted to use Factocrafty as one of it's cores.

**Comment by Wilyicaro** [comment]
Here is the server invite https://discord.gg/CTYHgp6ZZq :)
